name: first-workflo
on: workflow_dispatch
jobs:
  job1:
    runs-on: [ubuntu-latest]
    steps:
      - name: test
        run: echo "testing all files"
      - name: build
        run: .in echo "build the code"
  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        run: echo "Deploying the application"
      
    
